#!/usr/bin/env bash
# Script that install nginx in a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" > usr/share/nginx/html/index.html
