#!/usr/bin/env bash
# Script that install nginx in a new Ubuntu machine

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
chmod u+xwr /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
