#!/usr/bin/env bash
# Script tahat installs and configure HAproxy on your lb-01 server

apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
sed -i '$ a backend web-backend\n\tbalance roundrobin\n\tserver 34.73.202.194 34.73.202.194:80 check\n\tserver 54.82.109.39 54.82.109.39:80 check' /etc/haproxy/haproxy.cfg
service haproxy restart
