#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it
name="$(date +"%m-%d-%y").tar.gz"
sudo mysqldump -A -uroot -p"$1" | sudo tee backup.sql
tar -cvzf "$name" backup.sql
