#!/usr/bin/env bash
# Script that listens on port 80 of all the server’s active IPv4 IPs

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//g' /etc/nginx/sites-enabled/default
service nginx restart
