#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times,but for the 9th iteration,
# displays Holberton School and then Hi
n=1
while (( n <= 11 ))
do
	if (( n == 10 ))
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((n++))
done
