#!/usr/bin/env bash
# script that loops from 1 to 10 and: displays bad luck for the 4th
# loop iteration, displays good luck for the 8th loop iteration, displays
# Holberton School for the other iterations
n=1
while (( n <= 10 ))
do
	if (( n == 4 ))
	then
		echo "bad luck"
	elif ((n == 8))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((n++))
done
