#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes.
h=0
m=1
while (( h <= 12 ))
do
	echo "Hour: $h"
	while (( m <= 59 ))
	do
		echo "$m"
		((m++))
	done
	m=1
	((h++))
done
