#!/usr/bin/env bash
# Script that displays: the content of the current directory, in a list format,
# where only the part of the name after the first dash is displayed
for name_file in *
do
   echo "$name_file" | cut -d "-" -f 2
done
