#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts_tmp
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts_tmp
echo "8.8.8.8	facebook.com" >> ~/hosts_tmp
cp -f ~/hosts_tmp /etc/hosts
